# Generated by Django 5.2.1 on 2025-05-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "agency_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("agency_name", models.CharField(max_length=255)),
                ("agency_url", models.URLField()),
                ("agency_timezone", models.CharField(max_length=100)),
                ("agency_lang", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "agency_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "stop_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("stop_name", models.CharField(max_length=255)),
                ("stop_lat", models.FloatField()),
                ("stop_lon", models.FloatField()),
                ("stop_desc", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "route_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("route_short_name", models.CharField(max_length=50)),
                ("route_long_name", models.CharField(max_length=255)),
                ("route_type", models.IntegerField()),
                (
                    "agency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transporte.agency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shape_id", models.CharField(max_length=100)),
                ("shape_pt_lat", models.FloatField()),
                ("shape_pt_lon", models.FloatField()),
                ("shape_pt_sequence", models.IntegerField()),
            ],
            options={
                "unique_together": {("shape_id", "shape_pt_sequence")},
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "trip_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("service_id", models.CharField(max_length=100)),
                (
                    "trip_headsign",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("direction_id", models.IntegerField(blank=True, null=True)),
                ("shape_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transporte.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StopTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.TimeField()),
                ("departure_time", models.TimeField()),
                ("stop_sequence", models.IntegerField()),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transporte.stop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transporte.trip",
                    ),
                ),
            ],
            options={
                "unique_together": {("trip", "stop_sequence")},
            },
        ),
    ]
