# Generated by Django 5.2.1 on 2025-05-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "service_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("monday", models.BooleanField()),
                ("tuesday", models.BooleanField()),
                ("wednesday", models.BooleanField()),
                ("thursday", models.BooleanField()),
                ("friday", models.BooleanField()),
                ("saturday", models.BooleanField()),
                ("sunday", models.BooleanField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="FareAttribute",
            fields=[
                (
                    "fare_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("currency_type", models.CharField(max_length=10)),
                ("payment_method", models.IntegerField()),
                ("transfers", models.IntegerField()),
                (
                    "agency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transporte.agency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FareRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "destination_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contains_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transporte.fareattribute",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transporte.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("headway_secs", models.IntegerField()),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transporte.trip",
                    ),
                ),
            ],
        ),
    ]
