# Generated by Django 5.2.1 on 2025-05-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporte", "0002_calendar_fareattribute_farerule_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fareattribute",
            name="transfers",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
