# Generated by Django 5.2.1 on 2025-05-18 16:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transporte", "0003_alter_fareattribute_transfers"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326
            ),
        ),
    ]
