# Generated by Django 5.2.1 on 2025-06-12 00:00

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transporte", "0004_stop_geom"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoRequestCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("request_parameters", models.JSONField(default=dict)),
                (
                    "request_signature",
                    models.CharField(db_index=True, max_length=128),
                ),
                ("response_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["request_signature", "created_at"],
                        name="geo_cache_sig_created_idx",
                    ),
                ],
            },
        ),
    ]
